### PR TITLE
Update server tests to work with upgraded server devDependencies.

### PR DESCRIPTION
**Pull request by grempe**
- Upgrade mocha from 1.8.x to 2.3.x
- Upgrade should from 1.2.x to 7.1.x
- Remove mockery which was not used for server tests.
- Remove sinon which was not used for server tests.

Minor fixes to the existing server tests to work with upgraded packages.

### CODE REVIEW

**Comment by grempe** [comment]
Just rebased this branch off of your merge of my commit with jshint changes.  I then did a force push to this branch so should apply cleanly.

**Comment by grempe** [comment]
Interesting. This passes clean locally in phantomjs with 'make test' in the client dir (and updated phantoms and other depends). However, I was also just testing getting karma working with updated versions and config (using just Chrome for now) and I see the same errors that travis-ci just threw.

From travis-ci:

````
PhantomJS 1.9.8 (Linux 0.0.0): Executed 78 of 78 (7 FAILED) (32.303 secs / 26.999 secs)
TOTAL: 7 FAILED, 71 SUCCESS
1) should generate the correct fields from given values
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
2) should fail if containerNameHmacKey does not verify
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
3) should fail if hmacKey does not verify
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
4) should fail if secretKey does not verify
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
5) should fail if signKeyPrivate does not verify
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
6) should fail if pubKey is malformed
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
7) should fail if signKeyPub is malformed
     Account unravel()
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

````

From Chrome:

````
~/src/crypton/client (update-server-test-packages ✗)$ karma start my.conf.js --log-level debug --single-run
DEBUG [config]: Loading config /Users/glenn/src/crypton/client/my.conf.js
DEBUG [config]: autoWatch set to false, because of singleRun
DEBUG [plugin]: Loading karma-* from /usr/local/lib/node_modules
DEBUG [plugin]: Loading plugin /usr/local/lib/node_modules/karma-chrome-launcher.
DEBUG [plugin]: Loading plugin /usr/local/lib/node_modules/karma-firefox-launcher.
DEBUG [plugin]: Loading plugin /usr/local/lib/node_modules/karma-mocha.
DEBUG [plugin]: Loading plugin /usr/local/lib/node_modules/karma-safari-launcher.
DEBUG [watcher]: Resolved files:
	/usr/local/lib/node_modules/mocha/mocha.js
	/usr/local/lib/node_modules/karma-mocha/lib/adapter.js
	/Users/glenn/src/crypton/client/dist/crypton.js
	/Users/glenn/src/crypton/client/test/vendor/chai.js
	/Users/glenn/src/crypton/client/test/account.js
	/Users/glenn/src/crypton/client/test/card.js
	/Users/glenn/src/crypton/client/test/container.js
	/Users/glenn/src/crypton/client/test/core.js
	/Users/glenn/src/crypton/client/test/diff.js
	/Users/glenn/src/crypton/client/test/session.js
	/Users/glenn/src/crypton/client/test/transaction.js
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
DEBUG [temp-dir]: Creating temp dir at /var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/karma-32026324
DEBUG [launcher]: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --user-data-dir=/var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/karma-32026324 --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=32026324
DEBUG [web-server]: serving: /usr/local/lib/node_modules/karma/static/client.html
DEBUG [web-server]: serving: /usr/local/lib/node_modules/karma/static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/P_oFrMqG53fMkjVahAs8
DEBUG [karma]: A browser has connected on socket P_oFrMqG53fMkjVahAs8
DEBUG [web-server]: serving: /usr/local/lib/node_modules/karma/static/favicon.ico
INFO [Chrome 46.0.2490 (Mac OS X 10.10.5)]: Connected on socket P_oFrMqG53fMkjVahAs8 with id 32026324
DEBUG [launcher]: Chrome (id 32026324) captured in 2.007 secs
DEBUG [web-server]: serving: /usr/local/lib/node_modules/karma/static/context.html
DEBUG [web-server]: serving (cached): /usr/local/lib/node_modules/mocha/mocha.js
DEBUG [web-server]: serving (cached): /usr/local/lib/node_modules/karma-mocha/lib/adapter.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/dist/crypton.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/vendor/chai.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/account.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/card.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/container.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/core.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/diff.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/session.js
DEBUG [web-server]: serving (cached): /Users/glenn/src/crypton/client/test/transaction.js
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should generate the correct fields from given values FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:83:15)
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should fail if containerNameHmacKey does not verify FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:112:15)
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should fail if hmacKey does not verify FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:125:15)
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should fail if secretKey does not verify FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:138:15)
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should fail if signKeyPrivate does not verify FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:151:15)
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should fail if pubKey is malformed FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:168:15)
Chrome 46.0.2490 (Mac OS X 10.10.5) Account unravel() should fail if signKeyPub is malformed FAILED
	TypeError: Converting circular structure to JSON
	    at Object.stringify (native)
	    at Object.isomerProxy [as unravelAccount] (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:31)
	    at Account.unravel (base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:16)
	    at Context.<anonymous> (base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:185:15)
Chrome 46.0.2490 (Mac OS X 10.10.5): Executed 78 of 78 (7 FAILED) (2.557 secs / 2.066 secs)
DEBUG [karma]: Run complete, exiting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [launcher]: Process Chrome exited with code 0
DEBUG [temp-dir]: Cleaning temp dir /var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/karma-32026324
````

Chrome seems to provide some additional info regarding 'TypeError: Converting circular structure to JSON' which seems to be thrown by isomerize.js lib.

That led me here.  Which is where I am stuck right now:
http://stackoverflow.com/questions/4816099/chrome-sendrequest-error-typeerror-converting-circular-structure-to-json

Thoughts?

**Comment by grempe** [comment]
It always fails in this code (line 6311 in crypton.js):

https://github.com/SpiderOak/crypton/blob/master/client/src/vendor/isomer.js#L78

**Comment by grempe** [comment]
Perhaps @ecto can shed some light on why that might be failing in isomer.js.

I believe its a customized version of his repo code found here:

https://github.com/ecto/isomer

**Comment by daviddahl** [comment]
I'm thinking - now that I have looked into it a bit that newer webkit and blink just shit the bed when confronted with code that is unsafe eval, which this appears to do, no? https://github.com/SpiderOak/crypton/blob/master/client/src/vendor/isomer.js#L52

**Comment by daviddahl** [comment]
At the very least we need to excise this use of Blob + string to code -based workers. We just need to use a worker.

**Comment by grempe** [comment]
FYI, I ran the same Karma tests with Safari and Firefox.

````
[7 errs truncated]
Safari 8.0.8 (Mac OS X 10.10.5) Account unravel() should fail if signKeyPub is malformed FAILED
	JSON.stringify cannot serialize cyclic structures.
	stringify@[native code]
	isomerProxy@base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:40
	unravel@base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:30
	base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:185:22
````

````
Firefox 40.0.0 (Mac OS X 10.10.0) Account unravel() should fail if signKeyPub is malformed FAILED
	cyclic object value
	isomerProxy@base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:6311:26
	Account.prototype.unravel@base/dist/crypton.js?c816de2fad4e487b987ac350113ee6bd2100f157:570:3
	@base/test/account.js?733b0fb8df31600d82acba180900f33d5868fc03:185:7
````

I think the issue in this case is not specifically with WebWorkers, but something about the structure that is trying to be passed through JSON.stringify as talked about in the stackoverflow.com link I posted above. PhantomJS must be different, it passes with make test.

**Comment by daviddahl** [comment]
So, I am wondering what is in "arguments" and is it possible to step through this before it fails?:  https://github.com/SpiderOak/crypton/blob/master/client/src/vendor/isomer.js#L73

My point about the blob url is that debugging this is generally painful as it is written, with a proper worker in its own file it will reduce the complexity.

**Comment by grempe** [comment]
Huh, I thought I had it there. Tests pass locally using make test and with Karma in all Chrome, Firefox, and Safari.  But fails in travis-ci.  Argh.  I don't disagree with you David about removing isomerize in favor of a more modern generic approach.  I just don't have a lot of experience with Web Workers to tackle that I think.  I'll try to figure out this latest failure.

**Comment by grempe** [comment]
Boom! In the green.

**Comment by daviddahl** [comment]
Just read the Readme for Circular JSON, very cool. This has plagued us for some time!

**Comment by grempe** [comment]
Awesome, and I am now feeling more confident to mess around now that there is a full working set of tests that pass in the browser(s) as well as phantomjs. :-)

**Comment by ecto** [comment]
not sure where the circular json thing came from, but isomer is definitely a hack and should be removed

**Comment by daviddahl** [comment]
@ecto yeah, its weird, it makes me think there are not the arguments you expect and perhaps the callback is not a function after all (args.pop()) making the test timeout, etc?

**Comment by daviddahl** [comment]
@grempe Yes! this is some major work that I have put off too long. Thank you thank you thank you

**Comment by grempe** [comment]
:+1:

**Comment by grempe** [comment]
Notice always that it is the Account.unravel tests that caused the failure.  So there is something about what is being passed in from that test code that was always responsible for the circular error.

**Comment by daviddahl** [comment]
... which is always pointing to work.unravelAccount: https://github.com/SpiderOak/crypton/blob/master/client/src/work.js#L129
Which takes an Account object and callback

**Comment by daviddahl** [comment]
which leads me to believe it is a property that is an SJCL object that is the culprit: https://github.com/SpiderOak/crypton/blob/master/client/src/account.js#L89

**Pull request merged**
