### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by grempe**
Taking a major crack at using a real logger for NodeJS instead of the simple homegrown one.

All good apps need a good logger.

Cleans up test runs from showing console output and allows logging
to multiple outputs which are environment specific.

### CODE REVIEW

**Comment by grempe** [comment]
Here's another major patch bomb for your enjoyment. :-)

**Comment by daviddahl** [comment]
Can't wait to review this!

**Comment by grempe** [comment]
One minor issue I note with this (that I am fixing on another branch) is that if you run the server in the background with just 'cryptos-server start' it fails to run correctly since it needs the NODE_ENV to be specified.  Temp workaround is to use:

````
NODE_ENV=development crypton-server start
````

**Comment by daviddahl** [comment]
I was unable to view the logs when testing this patch. I must be doing something wrong:

`crypton-server start`
`crypton-server tail`  or 
`crypton-server logs` 

Does nothing for me. The server seems to work fine, however.

**Comment by daviddahl** [comment]
:+1:

**Pull request merged**
