### PR TITLE
Remove Otis docs NPM package. Can no longer be installed due to broken depends.

### LINKED ISSUE #399: 'make doc' doesn't work anymore. Old crufty Otis nom package is broken.
The Otis nom package depends on a github repo that no longer exists. Was last updated 3 years ago.  De-crufting after confirmation with @daviddahl

### PR DESCRIPTION
**Pull request by grempe**
Fixes #399 

It was last updated 3 years ago.
https://github.com/brynbellomy/otis

### CODE REVIEW

**Comment by daviddahl** [comment]
I think we switched to a ruby-based system last year, right @ecto ? I forgot what it is called (my old system was re-formatted and I lost it all). Speaking of which, I do need to get going on the Items API docs.

**Comment by ecto** [comment]
haha this is definitely for the best. i always cringed at https://github.com/SpiderOak/crypton/commit/967b47cdf7852e80d3bb2bbc0827a95bb3e7e1b0#diff-b67911656ef5d18c4ae36cb6741b7965L34

in my opinion, jekyll (which i think you're talking about) is the best option - you can write documentation in markdown and then use it for the website at the same time

**Comment by grempe** [comment]
If you are talking about API docs. I might suggest you try http://swagger.io

You create a description of your API in yaml and you get pretty output of your API and you can enforce various types and params. They have an online, or offline GUI editor that runs in the browser as well.

Writing API docs by hand is painful.

**Comment by daviddahl** [comment]
That looks very cool. /me reads.

**Comment by daviddahl** [comment]
http://editor.swagger.io/#/ ... wow

**Comment by grempe** [comment]
It generates client and server code in numerous languages from your API description as well. :-)

<mind blown />

**Pull request merged**
