### PR TITLE
Self signed cert

### LINKED ISSUE #388: Sample self-signed certificate included for server testing expired in 2013 breaking some browsers
The sample TLS certificates included in the repository and used for testing by the server expired in 2013. This prevents the certificate from being used for testing in some browsers (Safari) that don't appear to allow you to assign (override) trust to a self-signed certificate that is expired.  Updating this certificate with another self-signed cert that expires far in the future (e.g. 10 years) would be helpful.

See:

https://github.com/SpiderOak/crypton/tree/master/server/config

certificate_viewer__cam_pedersen_

### PR DESCRIPTION
**Pull request by grempe**
Fixes #388

Created with:

````
openssl genrsa -out localhost.key 2048

openssl req -new -x509 -key localhost.key -out localhost.cert -days
3650 -subj /CN=localhost

````

Copied the contents into the example .pem files in this repo and tested
in Safari on OS X which now allows the trust store to accept this cert
as an override.

### CODE REVIEW

**Comment by grempe** [comment]
Confirmed that Crypton examples using Safari on OS X now work with this new unexpired cert when you choose to manually trust this certificate when prompted.

**Comment by grempe** [comment]
Sorry about the extra merge commit included in this pull request. I would just ignore that and grab only commit b756bc7cc0a674e95fb2d8df52cb520d74d7dbde

**Comment by grempe** [comment]
:+1:

**Comment by daviddahl** [comment]
thanks again. Are you on Twitter?

**Comment by grempe** [comment]
No problem.  I am @grempe on twitter as well.  :-)  I'm working on some OS X notes for getting crypton up and running locally.  Will keep filing bugs or pull requests as needed.

**Comment by daviddahl** [comment]
Thanks. I just run everything in a VM - but it would be nice if the Postgres users, etc, wasn''t such a turd on OS X

**Comment by devgeeks** [comment]
:+1:

**Pull request merged**
