### PR TITLE
Enable running the Makefile and test scripts on OS X. All tests are passing.

### LINKED ISSUE #395: A developer should be able to run the Makefile's and test suite on OS X
The Makefiles and setup scripts assume Linux only.

### PR DESCRIPTION
**Pull request by grempe**
Fixes #395.

I feel kind of icky working with Makefiles. :smiley:

### CODE REVIEW

**Comment by daviddahl** [comment]
@grempe yes, it is icky. We want to transition to something else. anything else!

**Comment by daviddahl** [comment]
+1

**Comment by Bennyoak** [comment]
@grempe - Thanks for this and #393 
I was having an hell of a time setting up locally on my MBP

**Comment by grempe** [comment]
@Bennyoak Yeah, me too.  :-)  I was excited about crypton but quickly ran into some brick walls myself.  I fear lots of folks previously did as well since the (minimal) docs and scripts made some serious platform specific assumptions. The fact that the main website is also out of date for API and install docs didn't help.  :-(

**Pull request merged**
