### PR TITLE
dynamically load default db config

### PR DESCRIPTION
**Pull request by beane**

### CODE REVIEW

**Comment by daviddahl** [comment]
I will test this very soon. sorry for the delay!

**Comment by beane** [comment]
No worries! It doesn't do much anyway - but it would be good for the config files to actually get used instead of hardcoding values.

**Comment by grempe** [comment]
:+1:

**Comment by daviddahl** [comment]
Sorry for the delay

**Comment by beane** [comment]
first commit! :neckbeard:

**Comment by daviddahl** [comment]
:+1:

**Pull request merged**
